quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=false

quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=public
quarkus.flyway.validate-migration-naming=true
quarkus.flyway.clean-disabled=true

quarkus.http.port=8888
quarkus.http.test-port=0

quarkus.package.jar.type=fast-jar

quarkus.rest.path=/api/v1

%dev.quarkus.datasource.username=${PGUSER:search_api}
%dev.quarkus.datasource.password=${PGPASSWORD:search_api}
%dev.quarkus.datasource.reactive.url=postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:search_api}
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:search_api}

%prod.quarkus.datasource.username=${PGUSER}
%prod.quarkus.datasource.password=${PGPASSWORD}
%prod.quarkus.datasource.reactive.url=postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}
